declare const styles: {
    retroToolContainer: string;
    header: string;
    headerActions: string;
    btn: string;
    btnPrimary: string;
    btnSecondary: string;
    btnSmall: string;
    columnsContainer: string;
    column: string;
    columnHeader: string;
    columnTitle: string;
    columnPlaceholder: string;
    columnActions: string;
    columnBody: string;
    emptyState: string;
    card: string;
    cardActions: string;
    cardContent: string;
    privateCard: string;
    privateSection: string;
    privateSectionHeader: string;
    privateCards: string;
    newCardInput: string;
    modal: string;
    modalContent: string;
    modalHeader: string;
    modalBody: string;
    modalFooter: string;
    closeBtn: string;
    columnSettings: string;
    columnSetting: string;
};
export default styles;
